# This is a basic workflow to help you get started with Actions

name: karan


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  job_1:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
       
      - name: Run a one-line script
        run: python my.py

      
      
  job2:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: my name
        run: python myfolder/**