# This is a basic workflow to help you get started with Actions

name: karan


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
 job1:
   
    runs-on: ubuntu-latest


    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      
      
      - name: Run a one-line script
        run: echo Hello, world!

      
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
 job2:
   
    - runs-on: ubantu-latest
   - uses: actions/setup-python@v4

   steps: 
    -uses: actions/checkout@v3



    -name: my name
    -run: hello i am karan