name: Workflow
on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job_2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: My python 
        run: python my.py

  job_3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: My python 
        run: python myfolder/**








# # This is a basic workflow to help you get started with Actions

# name: karan


# on:
  
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  
#   workflow_dispatch:


# jobs:

#   job_1:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
#       - name: myname 
#         run: python my.py
  

#   job_2:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' 
#       - name: myname
#         run: python myfolder/**
        
      
      
#   # job2:
#   #   runs-on: ubuntu-latest

#   #   steps: 
#   #     - uses: actions/checkout@v3
#   #     - uses: actions/setup-python@v4
#   #       with:
#   #         python-version: '3.10' 
      
#   #     - name: my name
#   #       run: python myfolder/**